# Generated by Django 5.2.4 on 2025-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='user name')),
                ('email', models.EmailField(max_length=254, verbose_name='user_mail')),
                ('message', models.TextField(verbose_name='user_message!')),
            ],
            options={
                'verbose_name': 'contact',
            },
        ),
    ]
